server:
  ingress:
    enabled: true
    ingressClassName: alb
    annotations:
      alb.ingress.kubernetes.io/scheme: internet-facing
      alb.ingress.kubernetes.io/target-type: ip
    hosts:
    - cd.bacchus.io

configs:
  cm:
    url: https://cd.bacchus.io
    admin.enabled: false
    dex.config: |
      connectors:
      - type: github
        id: github
        name: GitHub
        config:
          clientID: 36bc63e3739b7724c29a
          clientSecret: $github-oauth:dex.github.clientSecret
          orgs:
          - name: bacchus-snu

  params:
    server.insecure: true

  rbac:
    policy.default: role:readonly
    policy.csv: |
      g, bacchus-snu:deputy, role:admin
