sources:
- ingress
domainFilters:
- bacchus.io
provider: cloudflare
extraArgs:
- --cloudflare-proxied
env:
- name: CF_API_TOKEN
  valueFrom:
    secretKeyRef:
      name: cloudflare
      key: CF_API_TOKEN
