env:
  DATA_FOLDER: config
  DISABLE_ICON_DOWNLOAD: true
  DOMAIN: https://vw.bacchus.io
  ORG_CREATION_USERS: null
  SIGNUPS_ALLOWED: true
  SIGNUPS_DOMAINS_WHITELIST: bacchus.snucse.org
  SIGNUPS_VERIFY: true
  SMTP_FROM: no-reply@snucse.org
  SMTP_HOST: smtp.gmail.com
  SMTP_PASSWORD: 
    valueFrom:
      secretKeyRef:
        name: vaultwarden-secret
        key: smtp-password
  SMTP_PORT: 587
  SMTP_SSL: true
  SMTP_USERNAME: no-reply@snucse.org
  TZ: Asia/Seoul
  WEBSOCKET_ENABLED: true

image:
  pullPolicy: IfNotPresent
  repository: vaultwarden/server
  tag: null

ingress:
  main:
    annotations:
      alb.ingress.kubernetes.io/scheme: internet-facing
      alb.ingress.kubernetes.io/target-type: ip
    enabled: true
    hosts:
    - host: vw.bacchus.io
      paths:
      - path: /
        pathType: Prefix
        service:
          port: 80
      - path: /notifications/hub/negotiate
        pathType: Prefix
        service:
          port: 80
      - path: /notifications/hub
        pathType: Prefix
        service:
          port: 3012
    ingressClassName: alb

persistence:
  config:
    enabled: true
    size: 16Gi
    retain: true

mariadb:
  enabled: false

postgresql:
  enabled: false

service:
  main:
    ports:
      http:
        port: 80
      websocket:
        enabled: true
        port: 3012

strategy:
  type: Recreate
